### ISSUE TITLE
To and From search bar not working 

### ISSUE THREAD

**Issue by Damanpreet3** [CSCI-150-LAB/Team3Repo#1]
Searchbar.html is working and giving suggestions whereas while I tried to collaborate the Searchbar.js with Navigation.html, it is not giving any suggestions. 
<img width="638" alt="Screen Shot 2020-10-30 at 2 53 54 PM" src="https://user-images.githubusercontent.com/57699102/97760213-d7692500-1abf-11eb-80c2-4937a3355f0c.png">
<img width="638" alt="Screen Shot 2020-10-30 at 2 54 24 PM" src="https://user-images.githubusercontent.com/57699102/97760216-d9cb7f00-1abf-11eb-8c4b-0ea7ed1a0128.png">

**Comment by DicheDiez10** [comment]
see attached test google maps folder with a search bar implemented with the maps
