### ISSUE TITLE
Warning after putting encryption of password

### ISSUE THREAD

**Issue by Damanpreet3** [CSCI-150-LAB/Team3Repo#2]
After encrypting the password, now we are able to verify and login using the encrypted password. But it gives me this warning, please review and let me know if you can help. 
<img width="617" alt="Screen Shot 2020-11-10 at 9 53 50 PM" src="https://user-images.githubusercontent.com/57699102/98778388-1d1ecb00-23a7-11eb-8a0a-d36ee11b6b7c.png">
<img width="689" alt="Screen Shot 2020-11-10 at 10 03 48 PM" src="https://user-images.githubusercontent.com/57699102/98778399-227c1580-23a7-11eb-8e98-f434508383dd.png">

**Comment by LQDJerry** [comment]
This issue is related to the Google Chrome browser. It has no correlation to our project. We can disregard this issue and continue testing and implementation with a different web browser.
