### ISSUE TITLE
Path Selection

### ISSUE THREAD

**Issue by DicheDiez10** [CSCI-150-LAB/Team3Repo#3]
![image](https://user-images.githubusercontent.com/47930238/99037917-89313880-2539-11eb-85eb-3bfee69c5fd2.png)

We need to be able to select the different route and the dark blue, or main route, to change to that new selected route. Basically set which route is the priority route, if the user chooses to select a route that is not

**Comment by LQDJerry** [comment]
I have fixed this issue. You are now able to select the preferred route the default route will be the fastest route. The preferred route is going to stand out from the other routes by having a full opacity while the others will be at a lower opacity.
